---

containerd_versioned_pkg:
  'latest': "{{ containerd_package }}"
  '1.2.4': "{{ containerd_package }}=1.2.4-1"
  'stable': "{{ containerd_package }}=1.2.4-1"
  'edge': "{{ containerd_package }}=1.2.4-1"

containerd_package_info:
  pkg_mgr: apt
  pkgs:
    - name: "{{ containerd_versioned_pkg[containerd_version | string] }}"
      force: yes

containerd_repo_key_info:
  pkg_key: apt_key
  url: '{{ containerd_ubuntu_repo_gpgkey }}'
  repo_keys:
    - 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

containerd_repo_info:
  pkg_repo: apt_repository
  repos:
    - >
       deb {{ containerd_ubuntu_repo_base_url }}
       {{ ansible_distribution_release|lower }}
       stable
